// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AnalyzeData, AnalyzeErrors, AnalyzeResponses, ApplyData, ApplyErrors, ApplyResponses, GetCandidatesData, GetCandidatesErrors, GetCandidatesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class AiMediaJanitorService {
    public static analyze<ThrowOnError extends boolean = false>(options?: Options<AnalyzeData, ThrowOnError>) {
        return (options?.client ?? client).post<AnalyzeResponses, AnalyzeErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/aimediajanitor/api/v1/analyze',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static apply<ThrowOnError extends boolean = false>(options?: Options<ApplyData, ThrowOnError>) {
        return (options?.client ?? client).post<ApplyResponses, ApplyErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/aimediajanitor/api/v1/apply',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static getCandidates<ThrowOnError extends boolean = false>(options?: Options<GetCandidatesData, ThrowOnError>) {
        return (options?.client ?? client).get<GetCandidatesResponses, GetCandidatesErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/aimediajanitor/api/v1/candidates',
            ...options
        });
    }
}
