// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44333' | (string & {});
};

export type ApplySuggestionRequest = {
    mediaKey: string;
    name?: string | null;
    altText?: string | null;
    caption?: string | null;
    targetFolderKey?: string | null;
};

export type ApplySuggestionResult = {
    mediaKey: string;
    success: boolean;
    appliedFields?: Array<string> | null;
    errorMessage?: string | null;
};

export type CandidatePage = {
    items: Array<MediaCandidate>;
    total: number;
};

export type FolderSuggestion = {
    name?: string | null;
    category?: string | null;
};

export type MediaAnalysisRequest = {
    mediaKey: string;
    language?: string | null;
};

export type MediaAnalysisSuggestion = {
    mediaKey: string;
    name?: string | null;
    altText?: string | null;
    caption?: string | null;
    folder?: FolderSuggestion | null;
    uncertain: boolean;
    note?: string | null;
};

export type MediaCandidate = {
    key: string;
    name: string;
    currentAltText?: string | null;
    folderPath?: string | null;
    thumbnailUrl?: string | null;
    mediaTypeAlias?: string | null;
    missingAlt: boolean;
    poorName: boolean;
};

export type AnalyzeData = {
    body?: MediaAnalysisRequest;
    path?: never;
    query?: never;
    url: '/umbraco/aimediajanitor/api/v1/analyze';
};

export type AnalyzeErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type AnalyzeResponses = {
    /**
     * OK
     */
    200: MediaAnalysisSuggestion;
};

export type AnalyzeResponse = AnalyzeResponses[keyof AnalyzeResponses];

export type ApplyData = {
    body?: ApplySuggestionRequest;
    path?: never;
    query?: never;
    url: '/umbraco/aimediajanitor/api/v1/apply';
};

export type ApplyErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type ApplyResponses = {
    /**
     * OK
     */
    200: ApplySuggestionResult;
};

export type ApplyResponse = ApplyResponses[keyof ApplyResponses];

export type GetCandidatesData = {
    body?: never;
    path?: never;
    query?: {
        missingAlt?: boolean;
        poorName?: boolean;
        skip?: number;
        take?: number;
    };
    url: '/umbraco/aimediajanitor/api/v1/candidates';
};

export type GetCandidatesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetCandidatesResponses = {
    /**
     * OK
     */
    200: CandidatePage;
};

export type GetCandidatesResponse = GetCandidatesResponses[keyof GetCandidatesResponses];
